name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Initialize JUCE submodule
        run: git submodule update --init --recursive

      - name: Install dependencies (macOS)
        run: |
          brew install liblo

      - name: Build the applications
        run: ./build.sh

      - name: Stage Binaries
        run: |
          mkdir osc-demo
          mv './build/juce_osc_app/OSCControlApp_artefacts/OSC Control Demo.app/Contents/MacOS/OSC Control Demo' osc-demo/osc-juce
          mv './build/osc_host' osc-demo/osc-pong

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OSCDemoMendeni-${{ matrix.os }}
          path: |
            osc-demo/

